apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
  labels:
    app: notification-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      containers:
      - name: notification-service
        image: stacksimplify/kube-notifications-microservice:4.0.0-AWS-XRay
        ports:
        - containerPort: 8096
        imagePullPolicy: Always
        env:
        - name: AWS_MAIL_SERVER_HOST
          value: "smtp-service"
        - name: AWS_MAIL_SERVER_USERNAME
          value: "AKIA3OFVNHBH2GGEXZBB"
        - name: AWS_MAIL_SERVER_PASSWORD
          value: "BO7C8rkGYn1qi1X0pTDkmOZRSWarSWRvbarGeE8vWvrC"
        - name: AWS_MAIL_SERVER_FROM_ADDRESS
          value: "oluwole.willy@yahoo.com"
